# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{multilogger}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Burke Libbey"]
  s.date = %q{2010-01-13}
  s.description = %q{Multilogger pattern matches incoming log messages to decide which log file to write them to.}
  s.email = %q{burke@burkelibbey.org}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "lib/multilogger.rb"
  ]
  s.homepage = %q{http://github.com/burke/multilogger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Split Rails logging into multiple log files}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

